# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: çš®å¡çš„åšå®¢ # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title:  çš®å¡çš„åšå®¢ # ç½‘ç«™çš„æ ‡é¢˜
  description: "çš®å¡ä¸˜çš„æ–‡ç« çš„Markdownæ ¼å¼å¤‡ä»½"
  language: zh  # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  banner:
    images:
      - "https://s2.loli.net/2025/01/25/PBvHFjr5yDu6t4a.webp"
      - "https://s2.loli.net/2025/01/25/6bKcwHZigzlM4mJ.webp"
      - "https://s2.loli.net/2025/01/25/H9WgEK6qNTcpFiS.webp"
      - "https://s2.loli.net/2025/01/25/njNVtuUMzxs81RI.webp"
      - "https://s2.loli.net/2025/01/25/tozsJ8QHAjFN3Mm.webp"
      - "https://s2.loli.net/2025/01/25/Pm89OveZq7NWUxF.webp"
      - "https://s2.loli.net/2025/01/25/UCYKvc1ZhgPHB9m.webp"
      - "https://s2.loli.net/2025/01/25/JjpLOW8VSmufzlA.webp"
    height: "60vh"
  # Banner é¡µé¢æ ‡é¢˜é…ç½®
  pages:
    home:
      title: "çš®å¡çš„åšå®¢"
      subtitle: "è¿·å­ã«ãªã£ãŸäººã¯è¿·å­ã«ãªã‚Šã€å‡ºä¼šã£ãŸäººã¯ã¾ãŸå‡ºä¼šã†"
      typewriterTexts: # æ–°å¢æ‰“å­—æœºæ–‡æœ¬é…ç½®  
        - "ğŸŒ³ è¿·å­ã«ãªã£ãŸäººã¯è¿·å­ã«ãªã‚Šã€å‡ºä¼šã£ãŸäººã¯ã¾ãŸå‡ºä¼šã†"
        - ""
        - ""
        - ""
    friend:
      title: "å‹äººå¸"
      subtitle: "è®°å½•é‚£äº›çè´µçš„å‹è°Šï¼Œåˆ†äº«å½¼æ­¤çš„æ•…äº‹"
    about:
      title: "å…³äºæˆ‘"
      subtitle: "ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»ä¸æŠ€æœ¯çš„æ™®é€šäººï¼"
    navigation:
      title: "ç½‘ç«™å¯¼èˆª"
      subtitle: "æ”¶è—çš„å¸¸ç”¨ç½‘ç«™å’Œå·¥å…·é“¾æ¥"
    anime:
      title: "è¿½ç•ª"
      subtitle: "è®°å½•å’Œåˆ†äº«æˆ‘å–œæ¬¢çš„åŠ¨æ¼«ä½œå“"
    project:
      title: "Projects"
      subtitle: "å±•ç¤ºä¸€äº›ä¸ªäººæ­å»ºçš„é¡¹ç›®ï¼Œæ¬è¿å·¥ï¼"
  menu: # èœå•é…ç½®
    - id: home
      text: æ–‡ç« 
      href: /
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: navigation
      text: å¯¼èˆª
      href: /navigation
      svg: "material-symbols:explore-outline"
      target: _self
      # å­èœå•é¡¹é…ç½®
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: å‹äººå¸
      href: /friends
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: about
      text: å…³äºçš®
      href: /aboutme
      svg: "material-symbols:info-outline-rounded"
      target: _self

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: Pikachu # ç”¨æˆ·å
  site: "https://coding.pika.net.cn/" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://github.com/PIKACHUIM"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/23090073"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://t.me/pikakapi"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"


  footer:
    social:
      - href: "https://github.com/PIKACHUIM"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/23090073"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://t.me/pikakapi"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"

# è¯„è®ºç³»ç»Ÿé…ç½®
comments:
  enable: false # æ˜¯å¦å¯ç”¨è¯„è®º
  type: giscus # giscus/waline/none
  giscus:
    repo: ""
    repoId: ""
    category: "General"
    categoryId: ""
    mapping: "pathname"
    lang: "zh-CN"
    inputPosition: "top"
    reactionsEnabled: "1"
    emitMetadata: "0"
    loading: "lazy"
  waline:
    serverURL: ""
    lang: "zh-CN"
    emoji:
      - "https://unpkg.com/@waline/emojis@1.1.0/weibo"
      - "https://unpkg.com/@waline/emojis@1.1.0/bilibili"
    meta: [ "nick", "mail", "link" ]
    requiredMeta: [ ]
    reaction: false
    pageview: false
# Umami ç»Ÿè®¡é…ç½®
umami:
  enable: false
  baseUrl: ""
  shareId: ""
  websiteId: ""
  timezone: "Asia/Shanghai"
